let buttonStart = document.getElementById('start'),
    values = document.querySelectorAll('body > div > div.main > div.result > div.result-table > div[class*="-value"]'),
    inputFields = document.getElementsByClassName('expenses-item'),
    approveButton1 = document.getElementsByTagName('button')[0],
    approveButton2 = document.getElementsByTagName('button')[1],
    calculateButton = document.getElementsByTagName('button')[2],
    optionalExpenses = document.querySelectorAll('body > div > div.main > div.data > input.optionalexpenses-item'),
    possibleIncome = document.getElementById('income'),
    savings = document.getElementById('savings'),
    sum = document.getElementById('sum'),
    percent = document.getElementById('percent'),
    year = document.querySelector('body > div > div.main > div.result > div.time-data > div.year > input'),
    month = document.querySelector('body > div > div.main > div.result > div.time-data > div.month > input'),
    day = document.querySelector('body > div > div.main > div.result > div.time-data > div.day > input');